version: "3.8"

services:
  fastapi_service:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    volumes:
      - ./api/:/api/
    command: uvicorn api:app --reload --workers 1 --host 0.0.0.0 --port 18000
    ports:
      - 18000:18000
